### ISSUE TITLE
Repeatedly loading generated.txt for each new line

### ISSUE THREAD

**Issue by torridgristle** [JermaSites/Jerma-AI-Chat#2]
On https://aichat.jerma.io/ it performs a GET request to https://aichat.jerma.io/generated.txt for each new line.

```js
const url = "https://aichat.jerma.io/generated.txt"
var getRandomMessage = async () => {
    const response = await fetch(url)
    var results = await gatherResponse(response)
    results = results.toString()
    const messages = results.split('\n')
    const randomMessage = messages[Math.floor(Math.random() * messages.length)]
    return (randomMessage)
};
```
Every 250 to 1500 milliseconds it's fetching an 8MiB txt file (cached after the first time), converting to string, splitting it by new line to make 176792 lines of text, choosing just one of them, returning it, and then doing it all over again.

I think it would be better to keep the messages loaded and choose from const messages rather than doing all this with an 8MiB file multiple times per second.

**Comment by sticks-stuff** [comment]
fixed
